# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fontSizeLabel = QtWidgets.QLabel(SettingsDialog)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.verticalLayout.addWidget(self.fontSizeLabel)
        self.fontSizeComboBox = QtWidgets.QComboBox(SettingsDialog)
        self.fontSizeComboBox.setObjectName("fontSizeComboBox")
        self.fontSizeComboBox.addItem("")
        self.fontSizeComboBox.addItem("")
        self.fontSizeComboBox.addItem("")
        self.verticalLayout.addWidget(self.fontSizeComboBox)
        self.difficultyLabel = QtWidgets.QLabel(SettingsDialog)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.verticalLayout.addWidget(self.difficultyLabel)
        self.difficultyComboBox = QtWidgets.QComboBox(SettingsDialog)
        self.difficultyComboBox.setObjectName("difficultyComboBox")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.verticalLayout.addWidget(self.difficultyComboBox)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(SettingsDialog)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(SettingsDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.fontSizeLabel.setText(_translate("SettingsDialog", "Select Font Size:"))
        self.fontSizeComboBox.setItemText(0, _translate("SettingsDialog", "Small"))
        self.fontSizeComboBox.setItemText(1, _translate("SettingsDialog", "Medium"))
        self.fontSizeComboBox.setItemText(2, _translate("SettingsDialog", "Large"))
        self.difficultyLabel.setText(_translate("SettingsDialog", "Select Difficulty Level:"))
        self.difficultyComboBox.setItemText(0, _translate("SettingsDialog", "Easy"))
        self.difficultyComboBox.setItemText(1, _translate("SettingsDialog", "Medium"))
        self.difficultyComboBox.setItemText(2, _translate("SettingsDialog", "Hard"))
        self.saveButton.setText(_translate("SettingsDialog", "Save"))
        self.cancelButton.setText(_translate("SettingsDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsDialog = QtWidgets.QDialog()
    ui = Ui_SettingsDialog()
    ui.setupUi(SettingsDialog)
    SettingsDialog.show()
    sys.exit(app.exec_())
